### PR TITLE
Configured params to request digital label as well as PDF

### PR DESCRIPTION
**Pull request by JevgenijusB**
Requesting Digital label (QR code) on a standard PDF label.

@vinted/shipping-backend

### CODE REVIEW

**Comment by JevgenijusB** [comment]
> What does it look like now versus before?

Now: [Vinted-FR-S10.pdf](https://github.com/vinted/chronopost/files/4454749/Vinted-FR-S10.pdf)
Before there was an empty space in QR code's place

**Comment by JevgenijusB** [comment]
Looks like this leads to an incorrect shipment number generation if parcel's destination is not FR. Still investigating the issue.

**Comment by zverseckas** [comment]
Does it look so blurry only to me?

**Comment by JevgenijusB** [comment]
> Does it look so blurry only to me?

Their example looks the same. Also blurry

**Pull request closed without merging**
